name: CI/CD Pipeline for Odoo ENCG

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v4
      # Step 3: Log in to Docker Hub (or another registry)
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/odoo-encg:latest .

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/odoo-encg:latest

  deploy:
    name: Deploy the Application
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs only after the build job is successful

    steps:
      # Step 1: Deploy to the server via SSH and run Docker Compose
      - name: Deploy to server
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ secrets.SERVER_IP }}                # IP of your server
          port: 22                                      # Default SSH port
          user: ${{ secrets.SERVER_USER }}              # SSH user
          key: ${{ secrets.PRIVATE_KEY }}               # Private SSH key stored in secrets
          first_ssh: |
            echo "Updating System"
            sudo apt-get update
          last_ssh: |
            pwd
            cd odoo-encg/
            docker compose down
            docker compose pull
            docker compose up -d
